platform :ios, '11.0'
use_frameworks!

target 'OktaNativeLogin' do
  pod 'OktaOidc'
  pod 'OktaAuthSdk'
  pod 'SVProgressHUD'
end

target 'OktaNativeLoginUITests' do
  pod 'OktaOidc'
  pod 'OktaAuthSdk'
  pod 'SVProgressHUD'
end
