name: Tests

on:
  push:
    paths:
      - '.github/workflows/tests.yaml'
      - 'browser-sign-in/**/*.swift'
      - 'Tests/**/*.swift'
    branches:
      - master
      - dev-*
      - release-*
  pull_request:
    branches:
      - master
      - dev-*
      - release-*
    paths:
      - '.github/workflows/tests.yaml'
      - 'browser-sign-in/**/*.swift'
      - 'Tests/**/*.swift'

env:
  DEVELOPER_DIR: /Applications/Xcode_13.3.app/Contents/Developer

jobs:
  SwiftBuild:
    name: Swift Unit Tests
    runs-on: macos-12
    timeout-minutes: 10
    steps:
    - name: Get swift version
      run: swift --version
    - uses: actions/checkout@master
    - name: Build
      run: swift build --build-tests
    - name: Test
      run: swift test

  XcodeBuild:
    name: Xcode Unit Tests
    runs-on: macos-12
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@master
    - name: Test browser-sign-in
      run: |
        set -o pipefail
        env NSUnbufferedIO=YES xcodebuild test \
          -derivedDataPath ../Build/DerivedData \
          -clonedSourcePackagesDirPath ../Build/ClonedSources \
          -resultBundlePath ../TestResults/browser-sign-in.xcresult \
          -scheme OktaBrowserSignIn \
          -sdk iphonesimulator \
          -destination "platform=iOS Simulator,OS=latest,name=iPhone 12" | xcpretty
    - name: Upload Test Results
      uses: actions/upload-artifact@v2
      with:
        path: ~/TestResults/*.xcresult
        name: XcodeBuild-Results
      if: success() || failure()