name: Tests

on:
  push:
    paths:
      - '.github/workflows/tests.yaml'
      - 'browser-sign-in/**/*.swift'
    branches:
      - master
      - dev-*
      - release-*
  pull_request:
    branches:
      - master
      - dev-*
      - release-*
    paths:
      - '.github/workflows/tests.yaml'
      - 'browser-sign-in/**/*.swift'

env:
  DEVELOPER_DIR: /Applications/Xcode_13.3.app/Contents/Developer

jobs:
  UITest-BrowserSignIn:
    name: Browser Sign In (iOS)
    runs-on: macos-12
    timeout-minutes: 10
    needs: 
      - XcodeBuild
      - SwiftBuild
    steps:
    - uses: actions/checkout@master
    - uses: ./.github/actions/setup-secrets
      with:
        okta_plist: "${{ secrets.TEST_OKTA_PLIST }}"
        test_configuration: "${{ secrets.TEST_CONFIGURATION }}"
    - name: Test
      run: |
        cd browser-sign-in
        xcodebuild \
            -derivedDataPath ~/Build/DerivedData \
            -clonedSourcePackagesDirPath ~/Build/ClonedSources \
            -resultBundlePath ~/TestResults/DeviceAuthSignIn-iOS.xcresult \
            -project OktaBrowserSignIn.xcodeproj \
            -scheme OktaBrowserSignIn \
            -destination platform=iOS\ Simulator,OS=15.5,name=iPhone\ 11 \
            clean test | xcpretty
    - name: Upload Test Results
      uses: actions/upload-artifact@v2
      with:
        path: ~/TestResults/*.xcresult
        name: BrowserSignIn-iOS-Results
      if: success() || failure()
  
  Results:
    name: Test Results
    runs-on: macos-12
    timeout-minutes: 5
    needs: 
      - UITest-BrowserSignIn
    if: always()
    steps:
    - name: Download Test Results
      uses: actions/download-artifact@v2
      with:
        path: ~/work/okta-mobile-swift/TestResults
    - uses: kishikawakatsumi/xcresulttool@v1
      with:
        path: |
          ../TestResults/XcodeBuild-Results/BrowserSignIn.xcresult
        title: UI Test Results
        show-passed-tests: false
